export const programmes = [
  {
    id: 1,
    name: "Business & Productivity",
    program: "Advanced Microsoft Excel",
    description: "Advance your Excel skills for reporting, formulas, pivot tables, dashboards, automation, and business analysis.",
    duration: "12 weeks",
    // icon: CiClock1,
    format: "Physical / Online virtual",
    price: "₦86,000",
    image: "/advanexcel.jpg",
    // icon2: IoArrowForward,
    view: "View programme",
    mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    title: "programms",
     enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
    details: "Produce better workplace reports",
    details1: "Analyze data more confidently",
    details2: "Improve office productivity and employability"

  },
  {
    id: 2,
    name: "Data Science & Analytics",
    program: "Data Science Course",
    description: "Automate repetitive work and business processes with generative AI, workflow platforms, APIs, agents, and responsible human oversight.",
    duration: "16 weeks",
    // icon: CiClock1,
    format: "Physical / Online virtual",
    price: "₦430,000",
    image: "/datasci.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 3,
    name: "UI/UX & Product Design",
    program: "UI/UX & Product Design",
    description: "Learn user research, wireframing, prototyping, usability testing, and portfolio-ready product design with Figma.",
    duration: "12 weeks",
    // icon: CiClock1,
    format: "Physical / Online virtual",
    price: "₦161,250",
    image: "/uiux.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 4,
    name: "Software Development",
    program: "Web Development with PHP & MySQL",
    description: "Learn dynamic website development with PHP, MySQL, forms, authentication, CRUD operations, and deployment basics.",
    duration: "16 weeks",
    // icon: CiClock1,
    format: "Physical / Online virtual",
    price: "₦430,000",
    image: "/php.jpg",
    // icon2: IoArrowForward,
    mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 5,
    name: "Creative & Media",
    program: "Videography",
    description: "Learn camera movement, lighting, sound, storytelling, editing, and practical video production for brands and events.",
    duration: "8 weeks",
    // icon: CiClock1,
    format: "On-campus / Hybrid",
    price: "₦215,000",
    image: "/multi.jpg",
    // icon2: IoArrowForward,
    view: "View programme",
    title: "programms",
    mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 6,
    name: "Digital Marketing",
    program: "Social Media Marketing",
    description: "Plan, create, publish, and measure social media campaigns for brands, SMEs, creators, and community growth.",
    duration: "8 weeks",
    // icon: CiClock1,
    format: "Online / Physical",
    price: "₦64,500",
    image: "/digitalmark.jpg",
    // icon2: IoArrowForward,
    view: "View programme",
    title: "programms",
    mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 7,
    name: "Software Development",
    program: "Python Programming",
    description: "Learn Python from the ground up with scripts, functions, files, APIs, data handling, testing, and practical projects.",
    // icon: CiClock1,
    duration: "12 weeks",
    format: "Physical / Online virtual",
    price: "₦215,000",
    image: "/pythons.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",

  },

  {
    id: 8,
    name: "Cybersecurity",
    program: "Certified Ethical Hacker (CEH)",
    description:
      "Prepare for ethical hacking and security testing with practical labs, attack-and-defence concepts, and CEH-aligned instruction.",
    // icon: CiClock1,
    duration: "16 weeks",
    format: "Physical / Online virtual",
    price: "₦1,290,000",
    image: "/cybersecurity.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 9,
    name: "Digital Marketing",
    program: "Content & Copywriting",
    description:
      "Learn persuasive writing for websites, social media, email, ads, and business communication.",
    // icon: CiClock1,
    duration: "8 weeks",
    format: "Online / Physical",
    price: "₦107,500",
    image: "/contentcreat.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 10,
    name: "Data Science & Analytics",
    program: "Data Analysis with Excel",
    description:
      "Learn Excel formulas, data cleaning, pivot tables, charts, dashboards, and practical reporting for business decisions.",
    // icon: CiClock1,
    duration: "12 weeks",
    format: "Online / Physical",
    price: "₦161,250",
    image: "/dataxcel.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
    details: "Produce better workplace reports",
    details1: "Analyze data more confidently",
    details2: "Improve office productivity and employability"

  },

  {
    id: 11,
    name: "Data Science & Analytics",
    program: "Data Analysis with Power BI",
    description:
      "Turn raw data into clear dashboards, models, and business insights using Microsoft Power BI..",
    // icon: CiClock1,
    duration: "8 weeks",
    format: "Online / Physical",
    price: "₦215,000",
    image: "/powerbi.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
    details: "Produce better workplace reports",
    details1: "Analyze data more confidently",
    details2: "Improve office productivity and employability"

  },

  {
    id: 12,
    name: "Software Development",
    program: "Full-Stack Web Development with Next.js",
    description:
      "Build modern full-stack web applications with HTML, CSS, JavaScript, React, Next.js, Node.js, databases, authentication, testing, and deployment.",
    // icon: CiClock1,
    duration: "16 weeks",
    format: "Online / Physical",
    price: "₦430,000",
    image: "/webmern.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 13,
    name: "Software Development",
    program: "Full-Stack Web Development with Django",
    description: "Create secure full-stack applications with Python, Django, REST APIs, React, databases, authentication, and deployment.",
    // icon: CiClock1,
    duration: "16 weeks",
    format: "Online / Physical",
    price: "₦430,000",
    image: "/django.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 14,
    name: "UI/UX & Product Design",
    program: "Graphics Design",
    description: "Learn visual communication, branding, typography, layout, and digital design with practical portfolio projects.",
    // icon: CiClock1,
    duration: "12 weeks",
    format: "Online / Physical",
    price: "₦161,250",
    image: "/graphic.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },

  {
    id: 15,
    name: "Business & Productivity",
    program: "Microsoft Office Specialist",
    description: "Build practical Word, Excel, PowerPoint, and productivity skills for office work and MOS certification readiness..",
    // icon: CiClock1,
    duration: "8 weeks",
    format: "Online / Physical",
    price: "₦107,500",
    image: "/office.jpg",
    // icon2: IoArrowForward,
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
    details: "Produce better workplace reports",
    details1: "Analyze data more confidently",
    details2: "Improve office productivity and employability"

  },

  {
    id: 16,
    name: "AI Automation",
    program: "Business & Productivity",
    description: "Build practical Word, Excel, PowerPoint, and productivity skills for office work and MOS certification readiness..",
    duration: "8 weeks",
    format: "Online / Physical",
    price: "₦107,500",
    image: "/Ai.jpg",
     mode: "Beginner-friendly",
    type:  "Format",
    time: "Duration",
    aid:"Learning support",
    view: "View programme",
    title: "programms",
    enroll: "Enroll for this course",
    askques: "Ask Admissions",
    curri: "Download curriculum",
  },
];
